style:
  tag:
    color: dark_green # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 5 # column width relative to the terminal window
    min_width: 20 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 20
    min_width: 30
  snippet:
    color: white
    width_percentage: 70

finder:
  command: fzf

cheats:
  paths:
    - /Users/tediak/.navi/cheats/tdk

shell:
  command: zsh
